### PR TITLE
Remove (not declared) dstypes assignement (not found in collectd API)

### PR DESCRIPTION
**Pull request by rdejoux**

### CODE REVIEW

**Review by winkidney — APPROVED** [review]

**Comment by winkidney** [comment]
Thanks for you contribution.

**Comment by rdejoux** [comment]
Thank you for the merge. If you can publish a new version on pypi that should be very nice to simplify the deployment of my test environment. Regards

**Comment by winkidney** [comment]
@rdejoux done.

**Comment by rdejoux** [comment]
@winkidney thanks

**Pull request merged**
